package servent.message;

public enum MessageType {
	NEW_NODE, WELCOME, SORRY, UPDATE, PUT, ASK_GET, TELL_GET, POISON,
	PING, KILL, LIST_FILES, LIST_FILES_RECEIVE, ASK_LIST_FILES, REMOVE_FILE, REMOVE_FILE_RECEIVE, FOLLOW, FOLLOW_FOUND,
	TOKEN, ASK_LIST_FILES_ERROR, COPY_DATA, PONG
}
